#version 460 core

struct Polygon {
    uint vertex1;
    uint vertex2;
    uint vertex3;
};

layout(local_size_x = 128) in;

layout(binding=6, std430) writeonly buffer PolygonsOut {
    Polygon polygonsOut[];
};

layout(binding=0, offset=0) uniform atomic_uint indexCounter;

layout(location=0) uniform mat4 viewMatrix;
layout(location=1) uniform uint polygonCount;
layout(location=2) uniform uint vertexOffset;

void main() {
    uint index = gl_GlobalInvocationID.x;
    uint base = index * 4u;

    if (index >= polygonCount) {
        return;
    }

    uint index1 = vertexOffset + base + 0u;
    uint index2 = vertexOffset + base + 1u;
    uint index3 = vertexOffset + base + 2u;
    uint index4 = vertexOffset + base + 3u;

    uint indexOut = atomicCounterAdd(indexCounter, 6u) / 3u;

    polygonsOut[indexOut + 0].vertex1 = index1;
    polygonsOut[indexOut + 0].vertex2 = index2;
    polygonsOut[indexOut + 0].vertex3 = index3;

    polygonsOut[indexOut + 1].vertex1 = index3;
    polygonsOut[indexOut + 1].vertex2 = index4;
    polygonsOut[indexOut + 1].vertex3 = index1;
}